apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: np0bbv5vg-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: np0bbv5vg-go 
  name: np0bbv5vg-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: np0bbv5vg-go 
